// ─── Form types ───────────────────────────────────────────
export const FORM_TYPES = [
  { id: "time",     label: "Время",        icon: "⏰", desc: "Фиксируешь конкретное время. Очки зависят от точности." },
  { id: "duration", label: "Длительность", icon: "⏱", desc: "Логируешь минуты." },
  { id: "meal",     label: "Питание",      icon: "🍽", desc: "3 приёма с интервалом. Таймер и напоминания." },
  { id: "boolean",  label: "Да / Нет",     icon: "✓",  desc: "Сделал — нажал." },
  { id: "steps",    label: "Шаги",         icon: "🚶", desc: "Считаешь шаги. Цель — дойти до нормы." },
  { id: "weight",   label: "Вес",          icon: "⚖",  desc: "Фиксируешь вес и % жира. Трекинг к цели." },
  { id: "tasks",    label: "Задачи",       icon: "☑",  desc: "3 приоритетных задачи на день." },
];

// ─── Categories ───────────────────────────────────────────
export const CATS = [
  { id: "body",  label: "Тело",   color: "#0F9D58" },
  { id: "mind",  label: "Разум",  color: "#2F80ED" },
  { id: "daily", label: "Режим",  color: "#7C3AED" },
];

// ─── Default forms (personal habits) ──────────────────────
export const DEFAULT_FORMS = [
  {
    id: "f1",
    name: "Подъём",
    principle: "Ранний старт — основа дня",
    type: "time",
    cat: "daily",
    pts: 100,
    target: "05:00",
    streak: 0,
    history: [],
    checkedToday: false,
    brokenToday: false,
  },
  {
    id: "f2",
    name: "Отбой",
    principle: "Качественный сон = качественный день",
    type: "time",
    cat: "daily",
    pts: 80,
    target: "21:00",
    streak: 0,
    history: [],
    checkedToday: false,
    brokenToday: false,
  },
  {
    id: "f3",
    name: "Прогулка",
    principle: "15 000 шагов в день",
    type: "steps",
    cat: "body",
    pts: 80,
    target: 15000,
    logged: 0,
    streak: 0,
    history: [],
    checkedToday: false,
  },
  {
    id: "f4",
    name: "Уборка",
    principle: "10 минут порядка каждый день",
    type: "duration",
    cat: "daily",
    pts: 60,
    target: 10,
    logged: 0,
    note: "",
    streak: 0,
    history: [],
    checkedToday: false,
  },
  {
    id: "f5",
    name: "Питание",
    principle: "Стабильный сахар = стабильные реакции",
    type: "meal",
    cat: "body",
    pts: 90,
    intervalH: 4,
    meals: [
      { l: "Завтрак", done: false, time: null, note: "" },
      { l: "Обед",    done: false, time: null, note: "" },
      { l: "Ужин",    done: false, time: null, note: "" },
    ],
    lastAt: null,
    streak: 0,
    history: [],
    checkedToday: false,
  },
  {
    id: "f6",
    name: "Чтение",
    principle: "1 час в день — 365 книг за жизнь",
    type: "duration",
    cat: "mind",
    pts: 90,
    target: 60,
    logged: 0,
    note: "",
    insights: [],
    streak: 0,
    history: [],
    checkedToday: false,
  },
  {
    id: "f7",
    name: "Вес",
    principle: "−6 кг за 3 месяца",
    type: "weight",
    cat: "body",
    pts: 70,
    goalKg: 6,
    goalDays: 90,
    startedAt: null,
    startWeight: null,
    logged: null,
    loggedFat: null,
    ropeMinutes: 0,
    ropeTarget: 10,
    history: [],
    checkedToday: false,
  },
  {
    id: "f8",
    name: "Дневник",
    principle: "Рефлексия — навык, не привычка",
    type: "boolean",
    cat: "mind",
    pts: 70,
    streak: 0,
    history: [],
    checkedToday: false,
    brokenToday: false,
  },
  {
    id: "f9",
    name: "Задачи",
    principle: "3 важных дела — хороший день",
    type: "tasks",
    cat: "mind",
    pts: 80,
    tasks: [
      { text: "", done: false },
      { text: "", done: false },
      { text: "", done: false },
    ],
    streak: 0,
    history: [],
    checkedToday: false,
  },
];

// ─── Month names ──────────────────────────────────────────
export const MONTH_NAMES = [
  "Январь","Февраль","Март","Апрель","Май","Июнь",
  "Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь",
];

export const WEEK_DAYS = ["Пн","Вт","Ср","Чт","Пт","Сб","Вс"];
